export const DASHBOARD_OVERVIEW_PATH = '/admin/dashboard/overview'
export const DASHBOARD_SUMMARY_PATH = '/admin/dashboard/summary'
export const DASHBOARD_ORDERS_PATH = '/admin/dashboard/orders'
export const DASHBOARD_FINANCE_PATH = '/admin/dashboard/finance'
export const DASHBOARD_REVIEW_QUEUES_PATH = '/admin/dashboard/review-queues'
export const DASHBOARD_APPROVAL_CENTER_PATH = '/admin/dashboard/approval-center'
export const DASHBOARD_TRENDS_PATH = '/admin/dashboard/trends'
