import type { PermissionKey } from "../types/common.types";

export const permissions: Record<string, PermissionKey> = {
  dashboard: "dashboard:read",
  approvals: "approvals:read",
  customers: "customers:read",
  vendors: "vendors:read",
  vendorOnboarding: "vendors:approve",
  orders: "orders:read",
  manualLogistics: "orders:update_status",
  payments: "payments:read",
  refunds: "payments:read",
  payouts: "payouts:read",
  reels: "reels:read",
  creatorMusic: "creator_music:read",
  influencers: "influencers:read",
  notifications: "notifications:read",
  content: "content:read",
  marketingCampaigns: "marketing_campaigns:read",
  reports: "reports:read",
  settings: "settings:read",
  featureFlags: "feature-flags:read",
  release2Settings: "settings:read",
  adminUsers: "admin_users:read",
  roles: "roles:read",
  permissions: "permissions:read",
  audit: "audit:read",
  profile: "admin_users:read",
};
