export const routePermissions = {
  adminUsers: 'admin_users:read',
  customers: 'vendors:read',
  vendors: 'vendors:read',
  vendorOnboarding: 'vendors:approve',
  orders: 'orders:read',
  manualLogistics: 'orders:update_status',
  payments: 'payments:read',
  payouts: 'payouts:read',
  reels: 'reels:read',
  notifications: 'rbac:manage',
  content: 'rbac:manage',
  reports: 'reports:read',
  settings: 'settings:read',
  audit: 'audit:read',
  profile: 'settings:read',
} as const
