export const routePaths = {
  login: "/login",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  accessDenied: "/access-denied",
  notFound: "/not-found",
  dashboard: "/app/dashboard",
  approvals: "/app/approvals",
  adminUsers: "/app/admin-users",
  roles: "/app/roles",
  customers: "/app/customers",
  vendors: "/app/vendors",
  vendorDocuments: "/app/vendor-documents",
  vendorDocumentReview: "/app/vendor-documents/:vendorId",
  vendorOnboarding: "/app/vendor-onboarding",
  orders: "/app/orders",
  manualLogistics: "/app/manual-logistics",
  payments: "/app/payments",
  refunds: "/app/refunds",
  payouts: "/app/payouts",
  reels: "/app/reels",
  creatorMusic: "/app/creator-music",
  influencers: "/app/influencers",
  influencerCampaigns: "/app/release-2/influencer-campaigns",
  notifications: "/app/notifications",
  content: "/app/content",
  customerAppHome: "/app/content/customer-app-home",
  customerAppHomeCarouselSlide:
    "/app/content/customer-app-home/hero-carousel/:slideId",
  marketingCampaigns: "/app/marketing-campaigns",
  marketingCampaignCreate: "/app/marketing-campaigns/new",
  marketingCampaignDetail: "/app/marketing-campaigns/:campaignId",
  reports: "/app/reports",
  settings: "/app/settings",
  release2Overview: "/app/release-2",
  featureFlags: "/app/release-2/feature-flags",
  featureFlagDetail: "/app/release-2/feature-flags/:featureKey",
  release2Settings: "/app/release-2/settings",
  release2SettingDetail: "/app/release-2/settings/:settingKey",
  customerRetention: "/app/release-2/customer-retention",
  audit: "/app/audit-logs",
  profile: "/app/profile",
} as const;
