export const routePaths = {
  login: '/login',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  accessDenied: '/access-denied',
  notFound: '/not-found',
  dashboard: '/app/dashboard',
  adminUsers: '/app/admin-users',
  roles: '/app/roles',
  customers: '/app/customers',
  customerWorkbenchPreview: '/app/customers/workbench-preview',
  vendors: '/app/vendors',
  vendorDocuments: '/app/vendor-documents',
  vendorOnboarding: '/app/vendor-onboarding',
  orders: '/app/orders',
  manualLogistics: '/app/manual-logistics',
  payments: '/app/payments',
  refunds: '/app/refunds',
  payouts: '/app/payouts',
  reels: '/app/reels',
  influencers: '/app/influencers',
  notifications: '/app/notifications',
  content: '/app/content',
  reports: '/app/reports',
  settings: '/app/settings',
  audit: '/app/audit-logs',
  profile: '/app/profile',
} as const
