export const routePermissions = {
  adminUsers: 'admin_users:read',
  dashboard: 'dashboard:read',
  customers: 'customers:read',
  vendors: 'vendors:read',
  vendorOnboarding: 'vendors:approve',
  orders: 'orders:read',
  manualLogistics: 'orders:update_status',
  payments: 'payments:read',
  refunds: 'payments:read',
  payouts: 'payouts:read',
  reels: 'reels:read',
  influencers: 'influencers:read',
  notifications: 'notifications:read',
  content: 'content:read',
  reports: 'reports:read',
  settings: 'settings:read',
  audit: 'audit:read',
  profile: 'admin_users:read',
  roles: 'roles:read',
} as const
